export const ProjectsList = [
    {
        title: 'My Portfolio Website',
        description: "Explore presentations of my projects, showcasing the fusion of creativity and technology. Built with HTML, CSS, Tailwind CSS, TypeScript, Next.js, Github Actions, Docker, Snyk, AWS, Nginx, and Ubuntu.",
        image: `${process.env.IMAGE_URL}/portfolio-image.jpg`,
        // siteUrl: 'https://jercarlocatallo.com',
        repositoryUrl: 'https://github.com/jercatallo/jer-carlo-catallo-website',
        techstacks: ['HTML', 'CSS', 'Tailwind', 'TypeScript', 'Next.js', 'Github Actions', 'Docker', 'Snyk', 'AWS','Nginx', 'Ubuntu'],
    },
    {
        title: 'barcode-tool',
        description: 'Lightweight npm package to Seamlessly integrate barcode generation and scanning into web applications for inventory management, product identification, and more. Powered by TypeScript, Jest, Rollup, and npm.',
        image: `${process.env.IMAGE_URL}/barcode-tool.jpg`,
        siteUrl: 'https://www.npmjs.com/package/barcode-tool',
        repositoryUrl: 'https://github.com/jercatallo/barcode-tool',
        techstacks: ['TypeScript', 'Jest', 'Rollup', 'npm'],
    },
    {
        title: 'Meta Little Lemon Application',
        description: 'This web application, built as part of a Meta front-end development course. The app simplifies the reservation process for restaurants. Developed with HTML, CSS, Tailwind CSS, JavaScript, React, Jest, Webpack, and Render.',
        image: `${process.env.IMAGE_URL}/little-lemon-app.jpg`,
        siteUrl: 'https://meta-front-end-developer-capstone-e1ky.onrender.com/',
        repositoryUrl: 'https://github.com/jercatallo/meta-front-end-developer-capstone',
        techstacks: ['HTML', 'CSS', 'Tailwind', 'JavaScript', 'React', 'Jest', 'Webpack', 'Render'],
    },
    {
        title: 'Github Repository Explorer',    
        description: 'Embark on a GitHub adventure, effortlessly exploring users public repositories with just their username! Powered by HTML, CSS, Tailwind CSS, TypeScript, React, Vite, and Render.',
        image: `${process.env.IMAGE_URL}/repository-explorer.jpg`,
        siteUrl: 'https://github-repositories-explorer.onrender.com/',
        repositoryUrl: 'https://github.com/jercatallo/github-repositories-explorer',
        techstacks: ['HTML', 'CSS', 'Tailwind', 'TypeScript', 'React', 'Vite', 'Render'],
    },
    {
        title: 'Dashboard Framework Demo App',
        description: 'Designed to streamline client-specific dashboard creation, leveraging reusable components for easy configuration of varying layouts, columns, and widget arrangements. Utilizes HTML, CSS, Tailwind, JavaScript, React, Jest, Webpack, and Render.',
        image: `${process.env.IMAGE_URL}/pokemon-app.jpg`,
        siteUrl: 'https://dashboard-framework-demo-app.onrender.com',
        repositoryUrl: 'https://github.com/jercatallo/dashboard-framework-demo-app',
        techstacks: ['HTML', 'CSS', 'Tailwind', 'JavaScript', 'React', 'Jest', 'Webpack', 'Render'],
    },
];
