export const Skills = [
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'Next.js',
    'SASS',
    'Tailwind CSS',
    'Figma',
    'Photoshop',
    'Node.js',
    'Express.js',
    'GraphQL',
    'MySQL',
    'MongoDB',
    'Jest',
    'webpack',
    'npm',
    'Git',
    'Chrome Developer Tools',
    'CI/CD',
    'Github Actions',
    'Snyk',
    'Docker',
    'Amazon Web Services (AWS)',
    'Heroku',
    'Netlify',
    'Github Pages',
    'Render',
    'macOS',
    'Windows',
    'Ubuntu',
    'Nginx',
    'Agile/Scrum',
];
