name: On Push to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Authenticate Docker with ECR
      run: |
        aws ${{secrets.AWS_ECR_VISIBILITY}} get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_DOMAIN_NAME}}/${{secrets.AWS_REPOSITORY_ID}}
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Build and push to ECR
      run: |
        docker build -t ${{secrets.AWS_REPOSITORY_URI}} .
        docker tag ${{secrets.AWS_REPOSITORY_URI}}:${{secrets.AWS_IMAGE_TAG}} ${{secrets.AWS_ECR_DOMAIN_NAME}}/${{secrets.AWS_REPOSITORY_ID}}/${{secrets.AWS_REPOSITORY_URI}}:${{secrets.AWS_IMAGE_TAG}}
        docker push ${{secrets.AWS_ECR_DOMAIN_NAME}}/${{secrets.AWS_REPOSITORY_ID}}/${{secrets.AWS_REPOSITORY_URI}}:${{secrets.AWS_IMAGE_TAG}}
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_AWS_REPOSITORY_URI: ${{secrets.AWS_REPOSITORY_URI}}

    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.AWS_EC2_HOST}}
        username: ${{secrets.AWS_EC2_USERNAME}}
        key: ${{secrets.AWS_EC2_PRIVATE_KEY}}
        script: |
          docker stop ${{secrets.AWS_REPOSITORY_URI}} || true
          docker rm ${{secrets.AWS_REPOSITORY_URI}} || true
          docker pull ${{secrets.AWS_ECR_DOMAIN_NAME}}/${{secrets.AWS_REPOSITORY_ID}}/${{secrets.AWS_REPOSITORY_URI}}:${{secrets.AWS_IMAGE_TAG}}
          docker run -d --name ${{secrets.AWS_REPOSITORY_URI}} -p ${{secrets.AWS_CONTAINER_PORT}}:${{secrets.AWS_CONTAINER_PORT}} ${{secrets.AWS_ECR_DOMAIN_NAME}}/${{secrets.AWS_REPOSITORY_ID}}/${{secrets.AWS_REPOSITORY_URI}}:${{secrets.AWS_IMAGE_TAG}}
